version: '3.1'

services:
  mysql:
      image: mysql:8.0.33
      container_name: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: teste
        MYSQL_DATABASE: "players"
      ports:
        - 3306:3306
      networks:
        - mysql-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
       pma_arbitrary: 1
       PMA_HOST: "mysql"
       PMA_POST: 3306
    networks:
      - mysql-network
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      - mysql-network

networks:
  mysql-network:
    driver: bridge